services:
  eshopdb:
    image: postgres

  distrubutedcache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:3.8-management
      

volumes:
  postgres_eshopdb: