services:
  eshopdb:
    image: postgres

  distrubutedcache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:3.8-management
  
  identity:
      image: quay.io/keycloak/keycloak:26.0.7

volumes:
  postgres_eshopdb: