services:
  eshopdb:
    image: postgres

  distributedcache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:3.8-management
  
  identity:
      image: quay.io/keycloak/keycloak:26.0.7

  api:
      image: ${DOCKER_REGISTRY-}api
      build:
        context: .
        dockerfile: src/Bootstrapper/Api/Dockerfile


volumes:
  postgres_eshopdb:
