services:
  eshopdb:
    image: postgres
    networks:
      - backend

  distributedcache:
    image: redis
    networks:
        - backend

  seq:
    image: datalust/seq:latest
    networks:
        - backend

  messagebus:
    image: rabbitmq:3.8-management
    networks:
        - backend
  
  identity:
      image: quay.io/keycloak/keycloak:26.0.7
      networks:
        - backend

  api:
      image: ${DOCKER_REGISTRY-}api
      networks:
        - backend
      build:
        context: .
        dockerfile: src/Bootstrapper/Api/Dockerfile

networks:
  backend:

volumes:
  postgres_eshopdb:
